# Generated by Django 3.0.5 on 2020-04-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
